#ifndef PARAM_CONFIG_H
#define PARAM_CONFIG_H

#define PM_CSPCONF  (1 << (PM_USER_FLAGS_OFFSET + 15))
#define PM_BOOTCONF (1 << (PM_USER_FLAGS_OFFSET + 14))

/* The following paramIDs are defined by Space Inventor */

#define PARAMID_GNDWDT 1

#define PARAMID_CSP_CAN0_ADDR 10
#define PARAMID_CSP_CAN0_MASK 11
// OBSOLETED #define PARAMID_CSP_RTABLE					 12
#define PARAMID_CSP_PRINT_CNF    13
#define PARAMID_CSP_CAN0_PROMISC 14
// OBSOLETED #define PARAMID_CSP_DFL_IFID                15
#define PARAMID_CSP_VERSION         16
#define PARAMID_CSP_DEDUP           17
#define PARAMID_CSP_KISS_ADDR       18
#define PARAMID_CSP_KISS_MASK       19
#define PARAMID_BOOT_IMG1           20
#define PARAMID_BOOT_IMG0           21
#define PARAMID_BOOT_IMG2           22
#define PARAMID_BOOT_IMG3           23
#define PARAMID_BOOT_CUR            24
#define PARAMID_BOOT_CNT            25
#define PARAMID_BOOT_ERR            26
#define PARAMID_CSP_CAN1_PROMISC    27
#define PARAMID_STDBUF_IN           28
#define PARAMID_STDBUF_OUT          29
#define PARAMID_SI_TEMP             30
#define PARAMID_SERIAL0             31
#define PARAMID_SERIAL1             32
#define PARAMID_SERIAL2             33
#define PARAMID_SERIAL3             34
#define PARAMID_CSP_RT_ADDR         35
#define PARAMID_CSP_RT_MASK         36
#define PARAMID_CSP_RT_IFID         37
#define PARAMID_CSP_CAN1_ADDR       38
#define PARAMID_CSP_CAN1_MASK       39
#define PARAMID_TIME_FACTOR         40
#define PARAMID_TFETCH_PRIMARY      41
#define PARAMID_TFETCH_SECONDARY    42
#define PARAMID_TFETCH_TIMEOUT      43
#define PARAMID_TFETCH_SYNCED       44
#define PARAMID_TFETCH_ERRORS       45
#define PARAMID_TFETCH_LAST         46
#define PARAMID_FREERTOS_PRINT_INFO 47
#define PARAMID_CSP_CAN0_ISDFL      48
#define PARAMID_CSP_CAN1_ISDFL      49
#define PARAMID_CSP_KISS_ISDFL      50

#define PARAMID_CSP_DBG_BUFFER_OUT   51
#define PARAMID_CSP_DBG_CONN_OUT     52
#define PARAMID_CSP_DBG_CONN_OVF     53
#define PARAMID_CSP_DBG_CONN_NOROUTE 54
#define PARAMID_CSP_DBG_INVAL_REPLY  55
#define PARAMID_CSP_DBG_ERRNO        56
#define PARAMID_CSP_DBG_CAN_ERRNO    57
#define PARAMID_CSP_DBG_RDP_PRINT    58
#define PARAMID_CSP_DBG_PACKET_PRINT 59

#define PARAMID_CSP_KISS_BAUDRATE 61

#define PARAMID_FPGA_SELECT     70
#define PARAMID_FPGA_LOAD_CRC   71
#define PARAMID_FPGA_READY      72
#define PARAMID_FPGA_LOAD_TIME  73
#define PARAMID_CSP_ETH_ADDR    76
#define PARAMID_CSP_ETH_MASK    77
#define PARAMID_CSP_ETH_ISDFL   78
#define PARAMID_CSP_ETH_PROMISC 79

/* ASTRA-LEO specific paramIDs: */

#define PARAMID_ALEO_CURRENT_MODE   100
#define PARAMID_ALEO_REQUESTED_MODE 101

#define PARAMID_SIPHRA0_REGS 0x5000
#define PARAMID_SIPHRA1_REGS 0x5001
#define PARAMID_SIPHRA2_REGS 0x5002
#define PARAMID_SIPHRA3_REGS 0x5003
#define PARAMID_SIPHRA4_REGS 0x5004
#define PARAMID_SIPHRA5_REGS 0x5005

#endif /* PARAM_CONFIG_H */
